[package]
name = "hacker-house-medellin/hhm-e2e"
version = "0.1.0"

[install]
dir = ".vendor/.zed"

[dependencies]
"hacker-house-medellin/hhm-clients" = "^0.1.0"
"hacker-house-medellin/hhm-interfaces" = "^0.1.0"
"hacker-house-medellin/hhm-libs" = "^0.1.0"
"hacker-house-medellin/hhm-cli" = "^0.1.0"
